# Generated by Django 4.2.4 on 2023-10-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_wtsuser_options_alter_wtsuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(default='No company', max_length=256),
        ),
    ]
