# Generated by Django 4.2.4 on 2024-03-03 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='factory',
            options={'verbose_name_plural': 'Производители'},
        ),
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name_plural': 'Семейства'},
        ),
        migrations.AlterModelOptions(
            name='revitfamily',
            options={'verbose_name_plural': 'ревит семейства'},
        ),
        migrations.AlterModelOptions(
            name='threedsmaxfamily',
            options={'verbose_name': '3DSmax family', 'verbose_name_plural': '3DSmax families'},
        ),
    ]
