# Generated by Django 4.2.4 on 2024-03-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_company_name_alter_wtsuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wtsuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
