# Generated by Django 4.2.4 on 2024-03-03 08:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_wtsuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wtsuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dd38713b-50b5-4e01-b406-689522bcc0a1'), editable=False, primary_key=True, serialize=False),
        ),
    ]
