# Generated by Django 4.2.4 on 2024-03-03 08:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_wtsuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wtsuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1653d60f-0221-4809-8ab7-ececddffd1aa'), editable=False, primary_key=True, serialize=False),
        ),
    ]
