# Generated by Django 4.2.4 on 2023-09-24 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevitFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('file', models.FileField(upload_to='revit_family')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='families.family')),
            ],
        ),
        migrations.AlterField(
            model_name='familyimage',
            name='family',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='families.family'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ThreeDSMaxFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('file', models.FileField(upload_to='threedsmax_family')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threedsmax_types', to='families.family')),
            ],
        ),
        migrations.CreateModel(
            name='RevitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('revit_family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revit_types', to='families.revitfamily')),
            ],
        ),
    ]
