# Generated by Django 4.2.4 on 2023-09-24 14:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('families', '0002_revitfamily_alter_familyimage_family_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='revitfamily',
            options={'ordering': ['-created_at', '-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='threedsmaxfamily',
            options={'ordering': ['-created_at', '-updated_at']},
        ),
        migrations.AddField(
            model_name='revitfamily',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revitfamily',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='revit_families', to='users.wtsuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revitfamily',
            name='editor',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.wtsuser'),
        ),
        migrations.AddField(
            model_name='revitfamily',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='threedsmaxfamily',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='threedsmaxfamily',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='threedsmax_families', to='users.wtsuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='threedsmaxfamily',
            name='editor',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.wtsuser'),
        ),
        migrations.AddField(
            model_name='threedsmaxfamily',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='revitfamily',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revit_families', to='families.family'),
        ),
        migrations.AlterField(
            model_name='threedsmaxfamily',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threedsmax_families', to='families.family'),
        ),
    ]
