# Generated by Django 4.2.4 on 2023-09-24 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('families', '0003_alter_revitfamily_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to='users.wtsuser'),
        ),
        migrations.AlterField(
            model_name='family',
            name='editor',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_edited', to='users.wtsuser'),
        ),
        migrations.AlterField(
            model_name='revitfamily',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to='users.wtsuser'),
        ),
        migrations.AlterField(
            model_name='revitfamily',
            name='editor',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_edited', to='users.wtsuser'),
        ),
        migrations.AlterField(
            model_name='threedsmaxfamily',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to='users.wtsuser'),
        ),
        migrations.AlterField(
            model_name='threedsmaxfamily',
            name='editor',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_edited', to='users.wtsuser'),
        ),
    ]
